// sp35/src/components/ConnectionStatus.tsx
import { useGameStore } from '@/stores/gameStore'

export default function ConnectionStatus() {
  const connectionState = useGameStore((s) => s.connectionState)
  const rtt = useGameStore((s) => s.streamStats.rtt)

  const state = connectionState.webrtc
  const color = state === 'connected' ? '#00ff88' : state === 'connecting' ? '#ffaa00' : '#ff3366'
  const label = state === 'connected' ? '已连接' : state === 'connecting' ? '连接中' : '未连接'

  return (
    <div className="flex items-center gap-2 rounded-full border border-white/10 bg-black/60 px-3 py-1.5 backdrop-blur-sm">
      <span
        className="inline-block h-2.5 w-2.5 rounded-full animate-pulse-glow"
        style={{ backgroundColor: color, boxShadow: `0 0 8px ${color}` }}
      />
      <span className="font-heading text-xs text-gray-300">{label}</span>
      {state === 'connected' && (
        <span className="font-heading text-xs text-[var(--cyan)]">{rtt}ms</span>
      )}
    </div>
  )
}

// sp25/src/components/ConnectionStatus.vue
<script setup lang="ts">
import type { ConnectionState } from '@/types'
import { Loader2 } from 'lucide-vue-next'

defineProps<{
  state: ConnectionState
}>()

const stateConfig: Record<ConnectionState, { dot: string; label: string; extra?: string }> = {
  connected: { dot: 'bg-cyber-green', label: '已连接' },
  connecting: { dot: 'bg-yellow-400', label: '连接中...' },
  reconnecting: { dot: 'bg-yellow-400', label: '重连中...', extra: 'animate-spin' },
  disconnected: { dot: 'bg-cyber-red', label: '已断开' },
}
</script>

<template>
  <div class="glass-panel rounded-lg px-3 py-1.5 flex items-center gap-2">
    <div class="relative">
      <span :class="['w-2 h-2 rounded-full block', stateConfig[state].dot]" />
      <span
        v-if="state === 'connected'"
        class="absolute inset-0 w-2 h-2 rounded-full bg-cyber-green animate-ping opacity-75"
      />
    </div>
    <Loader2 v-if="state === 'reconnecting'" class="w-3 h-3 text-yellow-400 animate-spin" />
    <span class="text-xs text-gray-400 font-source-sans">{{ stateConfig[state].label }}</span>
  </div>
</template>
